=== FranMartin04/EjerciciosLMGSI/ExamenesPrueba/futbol.dtd
<!ELEMENT futbol (ligas|CampeonesChampions)*>
<!ELEMENT ligas (#PCDATA|equipo)*>
<!ELEMENT equipo (Division|estadio|aficion)+>
<!ELEMENT Division (primera?,segunda?,(tercera|cuarta)?)>
<!ELEMENT primera EMPTY>
<!ELEMENT segunda EMPTY>
<!ELEMENT tercera EMPTY>
<!ELEMENT cuarta EMPTY>
<!ELEMENT CampeonesChampions EMPTY>
<!ELEMENT estadio EMPTY>
<!ELEMENT aficion EMPTY>
<!ATTLIST ligas nombre CDATA #REQUIRED
                pais CDATA #IMPLIED
                region CDATA #FIXED "Europa">
<!ATTLIST equipo regiÃ³n (Europa|America|Asia|Oceania|Africa) "Europa"
                nombre ID #REQUIRED
                rivalChampions IDREF #IMPLIED>
<!ATTLIST CampeonesChampions Campeones IDREFS #IMPLIED>
<!ENTITY presidente "Javier Tebas">
<!ENTITY % atributoNombre "nombre CDATA #REQUIRED">
<!ATTLIST estadio %atributoNombre;>
<!ATTLIST aficion %atributoNombre;>

=== FranMartin04/EjerciciosLMGSI/ExamenesPrueba/futbol.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE futbol SYSTEM "futbol.dtd">
<futbol>
    <ligas nombre="LaLiga" pais="España" region="Europa">
        Liga Española de &presidente;
        <equipo región="Europa" nombre="Madrid" rivalChampions="Liverpool">
            <Division>
                <primera></primera>
            </Division>
            <estadio nombre="Santiago Bernabéu"/>
            <aficion nombre="VIKINGOS"/>
        </equipo>
    </ligas>
    <ligas nombre="Premier League" pais="Inglaterra" region="Europa">
        Liga Española
        <equipo región="Europa" nombre="Liverpool" rivalChampions="Madrid">
            <Division>
                <primera></primera>
            </Division>
            <estadio nombre="Anfield"/>
            <aficion nombre="THE REDS"/>
        </equipo>
    </ligas>
    <CampeonesChampions Campeones="Madrid Liverpool"/>
</futbol>
