=== FranMartin04/EjerciciosLMGSI/XSD/crepusculo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"> 
<xs:element name="crepusculo" type="tipoSerie"/>
<xs:complexType name="tipoSerie" mixed="true">
    <xs:sequence>
      <xs:element name="personaje" maxOccurs="unbounded"/>
      <xs:element  name="parte" type="tipoParte" maxOccurs="unbounded"/>
      <xs:element name="acontecimiento"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="tipoAtributoNombre">
    <xs:attribute name="nombre" type="xs:string"/>
  </xs:complexType>
  <xs:complexType name="masAtributos">
    <xs:complexContent>
      <xs:extension base="tipoAtributoNombre">
        <xs:attribute name="relacionCon" type="xs:string"/>
        <xs:attribute name="enemigo" type="tipoAtributoEnemigoPorPattern"/>
        <xs:attribute name="rol" type="xs:string"/>
          </xs:extension>
    </xs:complexContent>
  </xs:complexType>  
  <xs:simpleType name="tipoAtributoEnemigoPorPattern">
    <xs:restriction base="xs:string">
      <xs:pattern value="((Emmett)|(Jacob)|( )){1,}"/>      
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="tipoParte">
    <xs:all>
      <xs:element name="nombre" type="tipoNombreDeParte"/>
      <xs:element name="escenario" minOccurs="0" type="tipoAtributoNombre"/>
      <xs:element name="pais" minOccurs="0" type="tipoAtributoNombre"/>
      <xs:element name="puntuacion" type="tipoPuntuación"/>
    </xs:all>
  </xs:complexType>
  <xs:simpleType name="tipoNombreDeParte">
    <xs:restriction base="xs:string">
      <xs:pattern value="[I]{1,5}[ - ]?.*"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="tipoPuntuación">
    <xs:sequence>
      <xs:element name="valoracion" type="xs:string" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="tipoLugar">
    <xs:choice>
      <xs:element name="acontecimiento" maxOccurs="unbounded" />
      <xs:element name="personasEnLugar" />
    </xs:choice>
    <xs:attribute name="nombre" type="xs:string"/>
  </xs:complexType>
</xs:schema>

=== FranMartin04/EjerciciosLMGSI/XSD/crepusculo.xml
<?xml version="1.0" encoding="UTF-8"?>
<crepusculo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="crepusculo.xsd">
    Crepusculo
    <personaje nombre="Edward" relacionCon="Bella" rol="protagonista"/>
    <personaje nombre="Jacob" enemigo="Emmett"/>
    <personaje nombre="Bella"/>
    <personaje nombre="Emmett" enemigo="Jacob"/>
    <parte>
		<nombre>I</nombre>
		<escenario nombre="Forks (WAshington)" />
		<puntuacion>
			<valoracion>Una web que le da un 3,4/5</valoracion>
			<valoracion>Una web que le da un 4,8/10</valoracion>
		</puntuacion>
        <pais />
	</parte>
    <acontecimiento></acontecimiento>
</crepusculo>
