=== FranMartin04/EjerciciosLMGSI/ExamenesPrueba/francisco_martin/cartascoleccionables.dtd
<!ELEMENT cartas (presentacion,personajes,mejoresHabilidades)+>
<!ELEMENT personajes (personaje*,lugardeltablero?,(dado|peonza)?)>
<!ELEMENT personaje (habilidad)>
<!ELEMENT lugardeltablero (#PCDATA|velocidadDelLugar)*>
<!ELEMENT dado EMPTY>
<!ELEMENT peonza EMPTY>
<!ELEMENT velocidadDelLugar (#PCDATA)>
<!ELEMENT habilidad EMPTY>
<!ELEMENT mejoresHabilidades EMPTY>
<!ELEMENT presentacion (nombredeljuego,nombredelaempresa)>
<!ELEMENT nombredeljuego EMPTY>
<!ELEMENT nombredelaempresa EMPTY>
<!ATTLIST personaje nombre (mago | caballero | arquero | curandero) "mago"
                    colorTraje CDATA #IMPLIED
                    altura CDATA #REQUIRED
                    hermandad CDATA #FIXED "Fuego">
<!ATTLIST habilidad nombre ID #REQUIRED
                    debilidad IDREF #IMPLIED>
<!ATTLIST mejoresHabilidades habilidades IDREFS #IMPLIED>
<!ENTITY suelo "Arenas Movedizas">
<!ENTITY % atributoNombre "nombre CDATA #REQUIRED">
<!ATTLIST nombredeljuego %atributoNombre;>
<!ATTLIST nombredelaempresa %atributoNombre;>

=== FranMartin04/EjerciciosLMGSI/ExamenesPrueba/francisco_martin/cartascoleccionables.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cartas SYSTEM "cartascoleccionables.dtd">
<cartas>
    <presentacion>
        <nombredeljuego nombre="Las aventuras deserticas con cartas" />
        <nombredelaempresa nombre="FranciscoEnterprise" />
    </presentacion>
    <personajes>
        <personaje nombre="mago" colorTraje="Rojo" altura="1,80" hermandad="Fuego">
            <habilidad nombre="Bola_Fuego" debilidad="Flecha_Divina" />
        </personaje>
        <personaje nombre="arquero" altura="1,60" colorTraje="Azul">
            <habilidad nombre="Flecha_Divina" debilidad="Bola_Fuego" />
        </personaje>
        <lugardeltablero> Desierto de &suelo; <velocidadDelLugar>Avance de dos casillas por cada
            tirada</velocidadDelLugar>
        </lugardeltablero>
        <dado />
    </personajes>
    <mejoresHabilidades habilidades="Bola_Fuego Flecha_Divina" />
</cartas>
